name: todolist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.30
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.0+1
  mobx: ^2.2.3
  lottie: ^2.7.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0


flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
